"""
EPMSSTS Speech Output QA & Validation Audit - Version 2
========================================================

Comprehensive validation using real speech audio generated by TTS.

Tests the complete pipeline:
1. Generate test speech via TTS
2. Feed through pipeline (STT -> Translation -> TTS)
3. Validate output at each stage

Senior AI Systems QA Engineer and Speech Pipeline Auditor
February 27, 2026
"""

import asyncio
import io
import json
import sys
import time
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple

import numpy as np
import soundfile as sf
from httpx import AsyncClient, ASGITransport

sys.path.insert(0, str(Path(__file__).parent))

from epmssts.api.main import app
from epmssts.services.tts.synthesizer import TtsService, TtsSynthesisRequest


class SpeechOutputQAValidatorV2:
    """Comprehensive QA validation using real speech audio."""
    
    def __init__(self):
        self.results = {
            "timestamp": time.time(),
            "methodology": "Using TTS-generated speech audio for realistic input",
            "test_cases": [],
            "audio_validation": {},
            "text_consistency": {},
            "language_validation": {},
            "emotion_validation": {},
            "round_trip_tests": [],
            "summary": {},
            "issues_found": [],
        }
        self.tts_service = None
    
    async def initialize(self):
        """Initialize TTS service for generating test audio."""
        try:
            print("  [INIT] Initializing TTS service for test data generation...")
            self.tts_service = TtsService()
            print(f"  [OK] TTS initialized. Engine: {self.tts_service._engine_kind}")
        except Exception as e:
            print(f"  [WARN] TTS initialization failed: {e}")
            self.results["issues_found"].append({
                "category": "initialization",
                "severity": "warning",
                "message": f"TTS init failed: {e}"
            })
    
    def generate_speech_audio(self, text: str, language: str = "en", emotion: str = "neutral") -> Optional[bytes]:
        """Generate realistic speech audio using TTS."""
        if not self.tts_service:
            return None
        
        try:
            request = TtsSynthesisRequest(
                text=text,
                language=language,
                emotion=emotion
            )
            wav_bytes = self.tts_service.synthesize(request)
            
            # Verify output
            if len(wav_bytes) > 100:  # Should be more than empty WAV
                return wav_bytes
            else:
                print(f"    [WARN] TTS generated empty audio for: '{text}'")
                return None
        except Exception as e:
            print(f"    [WARN] TTS synthesis failed: {e}")
            return None
    
    def analyze_audio_file(self, file_path: Path) -> Dict[str, Any]:
        """Analyze audio file properties."""
        if not file_path.exists():
            return {
                "exists": False,
                "error": "File does not exist"
            }
        
        file_size = file_path.stat().st_size
        
        try:
            # Read using soundfile
            audio_data, sample_rate = sf.read(file_path)
            
            # Handle mono/stereo
            if audio_data.ndim == 2:
                audio_data = audio_data.mean(axis=1)
            
            duration = len(audio_data) / sample_rate
            rms = float(np.sqrt(np.mean(np.square(audio_data))))
            peak = float(np.max(np.abs(audio_data)))
            
            # Check if silent
            is_silent = rms < 1e-5
            
            # Calculate approximate speech rate (zero crossings)
            zero_crossings = np.sum(np.abs(np.diff(np.sign(audio_data)))) / 2
            zcr = zero_crossings / duration if duration > 0 else 0
            
            return {
                "exists": True,
                "file_size_bytes": file_size,
                "file_size_kb": round(file_size / 1024, 2),
                "duration_sec": round(duration, 3),
                "sample_rate": sample_rate,
                "rms": round(rms, 6),
                "peak": round(peak, 4),
                "is_silent": is_silent,
                "zcr": round(zcr, 2),
                "waveform_valid": peak > 0.01 and not is_silent,
                "audio_channels": 1 if audio_data.ndim == 1 else audio_data.shape[1],
            }
        except Exception as e:
            return {
                "exists": True,
                "file_size_bytes": file_size,
                "error": f"Failed to analyze: {str(e)}"
            }
    
    async def test_1_audio_file_generation(self, client: AsyncClient):
        """Test 1: Audio file is generated correctly."""
        print("\n" + "="*80)
        print("TEST 1: AUDIO FILE GENERATION")
        print("="*80)
        print("Verifying: Audio files are generated and not empty")
        
        test_cases = [
            ("en", "Hello world, this is a test", "English input"),
            ("te", "నమస్కారం, ఇది ఒక పరీక్ష", "Telugu input"),
            ("hi", "नमस्ते, यह एक परीक्षण है", "Hindi input"),
        ]
        
        validation_results = []
        
        for target_lang, input_text, description in test_cases:
            print(f"\n  [{description}]")
            
            try:
                # Generate test audio using TTS
                print(f"    Generating test audio via TTS...")
                test_audio = self.generate_speech_audio(input_text, language="en", emotion="neutral")
                
                if not test_audio:
                    print(f"    [FAIL] Could not generate test audio")
                    validation_results.append({
                        "target_lang": target_lang,
                        "status": "skip",
                        "reason": "Test audio generation failed"
                    })
                    continue
                
                print(f"    Generated {len(test_audio)} bytes of test audio")
                
                # Send through pipeline
                print(f"    Sending through pipeline with target: {target_lang}")
                files = {"file": ("test.wav", test_audio, "audio/wav")}
                data = {"target_lang": target_lang}
                
                response = await client.post(
                    "/process/speech-to-speech",
                    files=files,
                    data=data,
                    timeout=120.0
                )
                
                if response.status_code != 200:
                    print(f"    Status: HTTP {response.status_code}")
                    validation_results.append({
                        "target_lang": target_lang,
                        "status": "fail",
                        "error": f"HTTP {response.status_code}"
                    })
                    continue
                
                result = response.json()
                session_id = result.get("session_id")
                
                if not session_id:
                    print(f"    [FAIL] No session_id in response")
                    validation_results.append({
                        "target_lang": target_lang,
                        "status": "fail",
                        "error": "Missing session_id"
                    })
                    continue
                
                # Find and analyze audio file
                outputs_dir = Path(__file__).parent / "outputs"
                audio_file = outputs_dir / f"{session_id}.wav"
                
                audio_analysis = self.analyze_audio_file(audio_file)
                
                # Perform checks
                checks = {
                    "file_exists": audio_analysis.get("exists", False),
                    "not_empty": audio_analysis.get("file_size_bytes", 0) > 44,  # WAV header minimum
                    "has_duration": audio_analysis.get("duration_sec", 0) > 0,
                    "not_silent": not audio_analysis.get("is_silent", True),
                    "waveform_valid": audio_analysis.get("waveform_valid", False),
                }
                
                all_passed = all(checks.values())
                
                # Print detailed results
                for check, passed in checks.items():
                    status_str = "[✓]" if passed else "[✗]"
                    print(f"    {status_str} {check}")
                
                if audio_analysis.get("duration_sec"):
                    print(f"       Duration: {audio_analysis['duration_sec']}s")
                if audio_analysis.get("file_size_kb"):
                    print(f"       File Size: {audio_analysis['file_size_kb']} KB")
                
                validation_results.append({
                    "target_lang": target_lang,
                    "status": "pass" if all_passed else "fail",
                    "checks": checks,
                    "analysis": audio_analysis,
                    "session_id": session_id,
                })
                
                print(f"    Result: {'[PASS]' if all_passed else '[FAIL]'}")
                
            except Exception as e:
                print(f"    [ERROR] {e}")
                validation_results.append({
                    "target_lang": target_lang,
                    "status": "fail",
                    "error": str(e)
                })
        
        self.results["audio_validation"] = {
            "test_cases": validation_results,
            "total": len(test_cases),
            "passed": sum(1 for r in validation_results if r["status"] == "pass"),
        }
        
        return validation_results
    
    async def test_2_text_consistency(self, client: AsyncClient):
        """Test 2: Verify input text -> translation -> TTS."""
        print("\n" + "="*80)
        print("TEST 2: TEXT CONSISTENCY CHECK")
        print("="*80)
        print("Verifying: Translation receives input, TTS receives translated text")
        
        # English -> Telugu
        target_lang = "te"
        test_text = "Hello, this is a test"
        
        print(f"\n  [English -> Telugu Translation & TTS]")
        
        try:
            # Generate English speech
            print(f"    Generating English speech...")
            test_audio = self.generate_speech_audio(test_text, language="en")
            
            if not test_audio:
                print(f"    [SKIP] Test audio generation failed")
                self.results["text_consistency"] = {"status": "skip"}
                return
            
            # Process through pipeline
            print(f"    Processing through pipeline...")
            files = {"file": ("test.wav", test_audio, "audio/wav")}
            data = {"target_lang": target_lang}
            
            response = await client.post(
                "/process/speech-to-speech",
                files=files,
                data=data,
                timeout=120.0
            )
            
            if response.status_code != 200:
                self.results["text_consistency"] = {
                    "status": "fail",
                    "error": f"HTTP {response.status_code}"
                }
                return
            
            result = response.json()
            
            # Extract values
            detected_lang = result.get("detected_language", "")
            transcript = result.get("transcript", "")
            translated_text = result.get("translated_text", "")
            session_id = result.get("session_id", "")
            
            print(f"    Original (via STT): '{transcript[:60]}'")
            print(f"    Translated: '{translated_text[:60]}'")
            print(f"    Target Lang: {target_lang}")
            
            # Verify translation
            translation_occurred = (
                detected_lang != target_lang and
                len(transcript.strip()) > 0 and
                len(translated_text.strip()) > 0
            )
            
            # Verify audio was generated for translated text
            outputs_dir = Path(__file__).parent / "outputs"
            audio_file = outputs_dir / f"{session_id}.wav"
            audio_analysis = self.analyze_audio_file(audio_file)
            
            checks = {
                "translation_different_from_source": translation_occurred,
                "translated_text_not_empty": len(translated_text.strip()) > 0,
                "tts_generated_audio": audio_analysis.get("waveform_valid", False),
            }
            
            all_passed = all(checks.values())
            
            for check, passed in checks.items():
                status_str = "[✓]" if passed else "[✗]"
                print(f"    {status_str} {check}")
            
            self.results["text_consistency"] = {
                "status": "pass" if all_passed else "partial",
                "checks": checks,
                "original_language": detected_lang,
                "target_language": target_lang,
                "translation_verified": all_passed,
            }
            
            print(f"    Result: {'[PASS]' if all_passed else '[PARTIAL]'}")
            
        except Exception as e:
            print(f"    [ERROR] {e}")
            self.results["text_consistency"] = {
                "status": "fail",
                "error": str(e)
            }
    
    async def test_3_target_language_validation(self, client: AsyncClient):
        """Test 3: Verify target language in output."""
        print("\n" + "="*80)
        print("TEST 3: TARGET LANGUAGE VALIDATION")
        print("="*80)
        print("Verifying: Output language matches target language")
        
        test_cases = [
            ("en", "Hello world, this is a test", "English output"),
            ("hi", "नमस्ते, यह एक परीक्षण है", "Hindi output"),
            ("te", "నమస్కారం, ఇది ఒక పరీక్ష", "Telugu output"),
        ]
        
        lang_results = []
        
        for target_code, test_text, description in test_cases:
            print(f"\n  [{description}]")
            
            try:
                # Generate source audio (use English as source)
                test_audio = self.generate_speech_audio(test_text, language="en")
                
                if not test_audio:
                    lang_results.append({
                        "target_lang": target_code,
                        "status": "skip",
                        "reason": "Audio generation failed"
                    })
                    continue
                
                # Process through pipeline
                files = {"file": ("test.wav", test_audio, "audio/wav")}
                data = {"target_lang": target_code}
                
                response = await client.post(
                    "/process/speech-to-speech",
                    files=files,
                    data=data,
                    timeout=120.0
                )
                
                if response.status_code != 200:
                    lang_results.append({
                        "target_lang": target_code,
                        "status": "fail",
                        "error": f"HTTP {response.status_code}"
                    })
                    continue
                
                result = response.json()
                target_lang_reported = result.get("target_language", "")
                translated_text = result.get("translated_text", "")
                session_id = result.get("session_id", "")
                
                # Analyze output audio
                outputs_dir = Path(__file__).parent / "outputs"
                audio_file = outputs_dir / f"{session_id}.wav"
                audio_analysis = self.analyze_audio_file(audio_file)
                
                # Check language consistency
                checks = {
                    "target_lang_correct": target_lang_reported == target_code,
                    "translation_present": len(translated_text.strip()) > 0,
                    "audio_generated": audio_analysis.get("exists", False),
                    "audio_valid": audio_analysis.get("waveform_valid", False),
                }
                
                # Script validation
                if target_code == "te":
                    has_script = any('\u0c00' <= c <= '\u0c7f' for c in translated_text)
                    checks["script_matches_language"] = has_script
                elif target_code == "hi":
                    has_script = any('\u0900' <= c <= '\u097f' for c in translated_text)
                    checks["script_matches_language"] = has_script
                elif target_code == "en":
                    has_script = any(32 <= ord(c) <= 126 for c in translated_text)
                    checks["script_matches_language"] = has_script
                
                all_passed = all(checks.values())
                
                for check, passed in checks.items():
                    status_str = "[✓]" if passed else "[✗]"
                    print(f"    {status_str} {check}")
                
                print(f"    Translated: '{translated_text[:50]}'")
                
                lang_results.append({
                    "target_language": target_code,
                    "status": "pass" if all_passed else "partial",
                    "checks": checks,
                    "translated_sample": translated_text[:100],
                })
                
                print(f"    Result: {'[PASS]' if all_passed else '[PARTIAL]'}")
                
            except Exception as e:
                print(f"    [ERROR] {e}")
                lang_results.append({
                    "target_language": target_code,
                    "status": "fail",
                    "error": str(e)
                })
        
        self.results["language_validation"] = {
            "test_cases": lang_results,
            "total": len(test_cases),
            "passed": sum(1 for r in lang_results if r["status"] == "pass"),
        }
    
    async def test_4_emotion_preservation(self, client: AsyncClient):
        """Test 4: Verify emotion affects speech."""
        print("\n" + "="*80)
        print("TEST 4: EMOTION PRESERVATION")
        print("="*80)
        print("Verifying: Emotion is detected and applied to output prosody")
        
        test_text = "Good morning, how are you today"
        
        emotion_results = []
        
        for emotion_label in ["happy", "sad", "neutral"]:
            print(f"\n  [{emotion_label.upper()}]")
            
            try:
                # Generate test audio  
                test_audio = self.generate_speech_audio(test_text, language="en", emotion=emotion_label)
                
                if not test_audio:
                    emotion_results.append({
                        "emotion": emotion_label,
                        "status": "skip",
                        "reason": "Audio generation failed"
                    })
                    continue
                
                # Process through pipeline (English -> English to preserve emotion for analysis)
                files = {"file": ("test.wav", test_audio, "audio/wav")}
                data = {"target_lang": "en"}
                
                response = await client.post(
                    "/process/speech-to-speech",
                    files=files,
                    data=data,
                    timeout=120.0
                )
                
                if response.status_code != 200:
                    emotion_results.append({
                        "emotion": emotion_label,
                        "status": "fail"
                    })
                    continue
                
                result = response.json()
                detected_emotion = result.get("detected_emotion", "neutral")
                emotion_confidence = result.get("confidence", 0.0)
                session_id = result.get("session_id", "")
                
                # Analyze output audio
                outputs_dir = Path(__file__).parent / "outputs"
                audio_file = outputs_dir / f"{session_id}.wav"
                audio_analysis = self.analyze_audio_file(audio_file)
                
                checks = {
                    "emotion_detected": len(detected_emotion) > 0,
                    "confidence_valid": 0.0 <= emotion_confidence <= 1.0,
                    "audio_generated": audio_analysis.get("exists", False),
                    "audio_valid": audio_analysis.get("waveform_valid", False),
                }
                
                all_passed = all(checks.values())
                
                for check, passed in checks.items():
                    status_str = "[✓]" if passed else "[✗]"
                    print(f"    {status_str} {check}")
                
                print(f"    Detected: {detected_emotion} (confidence: {emotion_confidence:.3f})")
                
                emotion_results.append({
                    "emotion": emotion_label,
                    "status": "pass" if all_passed else "partial",
                    "detected": detected_emotion,
                    "confidence": emotion_confidence,
                    "checks": checks,
                })
                
                print(f"    Result: {'[PASS]' if all_passed else '[PARTIAL]'}")
                
            except Exception as e:
                print(f"    [ERROR] {e}")
                emotion_results.append({
                    "emotion": emotion_label,
                    "status": "fail",
                    "error": str(e)
                })
        
        self.results["emotion_validation"] = {
            "test_cases": emotion_results,
            "total": len(["happy", "sad", "neutral"]),
            "passed": sum(1 for r in emotion_results if r["status"] == "pass"),
        }
    
    async def test_5_round_trip_pipeline(self, client: AsyncClient):
        """Test 5: Complete round-trip through pipeline."""
        print("\n" + "="*80)
        print("TEST 5: ROUND-TRIP PIPELINE VERIFICATION")
        print("="*80)
        print("Verifying: Complete EN->TE->EN->TE pipeline")
        
        round_trip_tests = []
        translation_pairs = [
            ("en", "te", "en", "English -> Telugu -> English"),
            ("en", "hi", "en", "English -> Hindi -> English"),
        ]
        
        for src, mid, target, description in translation_pairs:
            print(f"\n  [{description}]")
            
            try:
                test_text = "Hello world, this is a test"
                
                # Generate source audio
                source_audio = self.generate_speech_audio(test_text, language=src)
                
                if not source_audio:
                    round_trip_tests.append({
                        "translation_pair": description,
                        "status": "skip",
                        "reason": "Source audio generation failed"
                    })
                    continue
                
                # First hop: src -> mid
                print(f"    Step 1: {src.upper()} -> {mid.upper()}")
                files = {"file": ("test.wav", source_audio, "audio/wav")}
                data = {"target_lang": mid}
                
                response1 = await client.post(
                    "/process/speech-to-speech",
                    files=files,
                    data=data,
                    timeout=120.0
                )
                
                if response1.status_code != 200:
                    round_trip_tests.append({
                        "translation_pair": description,
                        "status": "fail",
                        "step": "first_translation"
                    })
                    continue
                
                result1 = response1.json()
                translated_mid = result1.get("translated_text", "")
                session_id_1 = result1.get("session_id", "")
                
                # Get intermediate audio
                outputs_dir = Path(__file__).parent / "outputs"
                audio_file_1 = outputs_dir / f"{session_id_1}.wav"
                mid_audio = audio_file_1.read_bytes() if audio_file_1.exists() else None
                
                if not mid_audio:
                    round_trip_tests.append({
                        "translation_pair": description,
                        "status": "fail",
                        "step": "intermediate_audio_generation"
                    })
                    continue
                
                # Second hop: mid -> target
                print(f"    Step 2: {mid.upper()} -> {target.upper()}")
                files = {"file": ("test.wav", mid_audio, "audio/wav")}
                data = {"target_lang": target}
                
                response2 = await client.post(
                    "/process/speech-to-speech",
                    files=files,
                    data=data,
                    timeout=120.0
                )
                
                if response2.status_code != 200:
                    round_trip_tests.append({
                        "translation_pair": description,
                        "status": "fail",
                        "step": "second_translation"
                    })
                    continue
                
                result2 = response2.json()
                final_audio_path = outputs_dir / f"{result2.get('session_id', '')}.wav"
                final_audio_analysis = self.analyze_audio_file(final_audio_path)
                
                # Checks
                checks = {
                    "intermediate_translation_valid": len(translated_mid.strip()) > 0,
                    "intermediate_audio_valid": audio_file_1.exists() and audio_file_1.stat().st_size > 44,
                    "final_audio_valid": final_audio_analysis.get("waveform_valid", False),
                    "full_pipeline_executed": result2.get("detected_language") is not None,
                }
                
                all_passed = all(checks.values())
                
                for check, passed in checks.items():
                    status_str = "[✓]" if passed else "[✗]"
                    print(f"    {status_str} {check}")
                
                round_trip_tests.append({
                    "translation_pair": description,
                    "status": "pass" if all_passed else "partial",
                    "checks": checks,
                    "intermediate": translated_mid[:50],
                })
                
                print(f"    Result: {'[PASS]' if all_passed else '[PARTIAL]'}")
                
            except Exception as e:
                print(f"    [ERROR] {e}")
                round_trip_tests.append({
                    "translation_pair": description,
                    "status": "fail",
                    "error": str(e)
                })
        
        self.results["round_trip_tests"] = {
            "test_cases": round_trip_tests,
            "total": len(translation_pairs),
            "passed": sum(1 for r in round_trip_tests if r["status"] == "pass"),
        }
    
    def generate_qa_report(self) -> str:
        """Generate comprehensive QA report."""
        print("\n" + "="*80)
        print("FINAL QA VALIDATION REPORT")
        print("="*80)
        
        # Summary of each test category
        test_results = {}
        
        # Test 1: Audio File Generation
        audio_val = self.results.get("audio_validation", {})
        audio_passed = audio_val.get("passed", 0)
        audio_total = audio_val.get("total", 0)
        test_results["Test 1 (Audio Generation)"] = (audio_passed, audio_total)
        print(f"\n  [TEST 1] Audio File Generation: {audio_passed}/{audio_total} PASSED")
        
        # Test 2: Text Consistency
        text_cons = self.results.get("text_consistency", {})
        text_status = text_cons.get("status", "unknown").upper()
        test_results["Test 2 (Text Consistency)"] = (1 if text_status == "PASS" else 0, 1)
        print(f"  [TEST 2] Text-to-Speech Consistency: {text_status}")
        
        # Test 3: Language Validation
        lang_val = self.results.get("language_validation", {})
        lang_passed = lang_val.get("passed", 0)
        lang_total = lang_val.get("total", 0)
        test_results["Test 3 (Language Validation)"] = (lang_passed, lang_total)
        print(f"  [TEST 3] Target Language Validation: {lang_passed}/{lang_total} PASSED")
        
        # Test 4: Emotion Preservation
        emotion_val = self.results.get("emotion_validation", {})
        emotion_passed = emotion_val.get("passed", 0)
        emotion_total = emotion_val.get("total", 0)
        test_results["Test 4 (Emotion)"] = (emotion_passed, emotion_total)
        print(f"  [TEST 4] Emotion Preservation: {emotion_passed}/{emotion_total} PASSED")
        
        # Test 5: Round-trip
        round_trip = self.results.get("round_trip_tests", {})
        rt_passed = round_trip.get("passed", 0)
        rt_total = round_trip.get("total", 0)
        test_results["Test 5 (Round-trip)"] = (rt_passed, rt_total)
        print(f"  [TEST 5] Round-Trip Pipeline: {rt_passed}/{rt_total} PASSED")
        
        # Overall verdict
        total_passed = sum(p for p, t in test_results.values())
        total_tests = sum(t for p, t in test_results.values())
        
        # Determine verdict
        if total_passed == total_tests and all(text_status == "PASS" for text_status in [text_cons.get("status", "").upper()]):
            verdict = "PASS"
            symbol = "✅"
        elif total_passed >= total_tests * 0.7:
            verdict = "PARTIAL"
            symbol = "⚠️"
        else:
            verdict = "FAIL"
            symbol = "❌"
        
        print(f"\n  Overall: {total_passed}/{total_tests} test cases PASSED")
        print(f"\n  {symbol} FINAL VERDICT: {verdict}")
        print("="*80)
        
        # Issues found
        if self.results.get("issues_found"):
            print(f"\n  ISSUES FOUND:")
            for issue in self.results["issues_found"]:
                print(f"    - [{issue.get('severity', 'INFO')}] {issue.get('message', '')}")
        
        # Recommendations
        print(f"\n  RECOMMENDATIONS:")
        if verdict == "PASS":
            print(f"    ✓ System is functioning correctly")
            print(f"    ✓ Speech output pipeline verified end-to-end")
            print(f"    ✓ Audio files are generated with correct format")
            print(f"    ✓ Translation pipeline working as expected")
        elif verdict == "PARTIAL":
            print(f"    ⚠ Some functionality is working correctly")
            print(f"    ⚠ Review failed test cases above")
            print(f"    ⚠ May require additional debugging or input validation")
        else:
            print(f"    ✗ Critical issues detected")
            print(f"    ✗ System may not be production-ready")
            print(f"    ✗ Recommend investigation of failed stages")
        
        self.results["summary"] = {
            "total_test_cases": total_tests,
            "passed_test_cases": total_passed,
            "verdict": verdict,
            "timestamp": time.time(),
        }
        
        # Save detailed report
        report_path = Path(__file__).parent / "outputs" / "qa_validation_report_v2.json"
        report_path.parent.mkdir(exist_ok=True)
        with open(report_path, "w") as f:
            json.dump(self.results, f, indent=2, default=str)
        
        print(f"\n  Detailed report: {report_path}\n")
        
        return verdict


async def main():
    """Run comprehensive QA validation."""
    print("="*80)
    print("EPMSSTS SPEECH OUTPUT QA & VALIDATION AUDIT - VERSION 2")
    print("Senior AI Systems QA Engineer and Speech Pipeline Auditor")
    print("="*80)
    
    validator = SpeechOutputQAValidatorV2()
    
    try:
        async with app.router.lifespan_context(app):
            transport = ASGITransport(app=app)
            async with AsyncClient(transport=transport, base_url="http://test") as client:
                
                # Initialize TTS for test data generation
                await validator.initialize()
                
                # Run all tests
                await validator.test_1_audio_file_generation(client)
                await validator.test_2_text_consistency(client)
                await validator.test_3_target_language_validation(client)
                await validator.test_4_emotion_preservation(client)
                await validator.test_5_round_trip_pipeline(client)
        
        # Generate report
        verdict = validator.generate_qa_report()
        
        return verdict.upper() == "PASS"
        
    except Exception as e:
        print(f"\nFatal error: {e}")
        import traceback
        traceback.print_exc()
        return False


if __name__ == "__main__":
    try:
        success = asyncio.run(main())
        sys.exit(0 if success else 1)
    except KeyboardInterrupt:
        print("\n\nValidation interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\nFatal error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
